services:
  - type: web
    name: signaling-server
    env: node
    plan: free
    branch: master
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
